language: node_js
node_js:
  - "13"
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.69/hugo_0.69_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - npm ci

script: ./publish.sh

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
